---
- name: "Be sure to add PPolicy Overlay"
  ldap_entry:
    dn: olcOverlay={1}ppolicy,olcDatabase={1}mdb,cn=config
    objectClass:
      - olcConfig
      - olcOverlayConfig
      - olcPPolicyConfig
      - top
    attributes:
      olcOverlay: "ppolicy"
      olcPPolicyDefault: "cn=default,ou=policies,{{ ldap['basedn'] }}"
