---

- name: "Be sure to add 'memberof' overlay"
  ldap_entry:
    dn: "olcOverlay={0}memberof,olcDatabase={1}mdb,cn=config"
    objectClass:
      - olcConfig
      - olcMemberOf
      - olcOverlayConfig
      - top
    attributes:
      olcOverlay: "memberof"
      olcMemberOfDangling: "ignore"
      olcMemberOfRefInt: "TRUE"
      olcMemberOfGroupOC: "groupOfNames"
      olcMemberOfMemberAD: "member"
      olcMemberOfMemberOfAD: "memberOf"

