---

- name: "Be sure to configure the OpenLDAP ACL"
  ldap_attr:
   dn: "olcDatabase={1}mdb,cn=config"
   name: olcAccess
   values:
     - >-
       {0}to *
       by dn.exact=gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth manage
       by * break
     - >-
       {1}to attrs=userPassword
       by self write
       by anonymous auth
       by dn="cn=admin,{{ ldap['basedn'] }}" write
       by * none
     - >-
       {2}to dn.base=""
       by anonymous auth
       by * read
     - >-
       {3}to dn.base="cn=Subschema"
       by * read
     - >-
       {4}to *
       by dn.exact="cn=idpuser,ou=system,{{ ldap['basedn'] }}" read
       by anonymous auth
       by self read
   state: exact
