---
# Tasks for openLDAP Restoration
- name: "RESTORE - Retrieve LDAP backup into {{ files_dir }}/{{ fqdn }}/openldap/restore/ldap-users.ldif.gz"
  command: "rsync -avzh {{ bck_uri }}/{{ fqdn }}/{{ host_bck_path }}/ldap-users.ldif.gz {{ files_dir }}/{{ fqdn }}/openldap/restore/ldap-users.ldif.gz"
  delegate_to: 127.0.0.1
  when:
    - bck_uri is defined
    - bck_uri != ""
    - host_bck_path is defined
    - host_bck_path != ""

- name: "RESTORE - Load LDAP backup on IdP"
  copy:
   src: "{{ files_dir }}/{{ fqdn }}/openldap/restore/ldap-users.ldif.gz"
   dest: "/root/ldap-users.ldif.gz"
   owner: "root"
   group: "root"
   mode: "0600"

- name: "RESTORE - Extract LDAP backup"
  command: "gunzip /root/ldap-users.ldif.gz"

- name: "RESTORE - Assign to ldap-users.ldif the right permissions"
  file:
   dest: "/root/ldap-users.ldif"
   owner: "root"
   group: "root"
   mode: "600"

- name: "RESTORE - Empty the people and groups Directory branches"
  shell: "ldapdelete -r -QY EXTERNAL -H ldapi:/// ou=people,{{ ldap['basedn'] }} ou=groups,{{ ldap['basedn'] }}"
  ignore_errors: True

- name: "RESTORE - Stop SLAPD service before restoring the entries"
  service:
   name: slapd
   state: stopped

- name: "RESTORE - Restore openLDAP entries"
  command: "slapadd -c -l /root/ldap-users.ldif"

- name: "RESTORE - CLEANUP - Remove the ldap-users.ldif backup file"
  file:
   dest: "/root/ldap-users.ldif"
   state: "absent"

- name: "RESTORE - CLEANUP - Remove the ldap-users.ldif backup file"
  file:
   dest: "/root/ldap-users.ldif.gz"
   state: "absent"

- name: "RESTORE - Start SLAPD service"
  service:
   name: slapd
   state: started

- name: "RESTORE - Check if the HOST YAML file is encrypted with Vault"
  command: "cat {{ inventory_dir }}/host_vars/{{ inventory_hostname }}.yml"
  delegate_to: 127.0.0.1
  register: host_yaml

- name: "RESTORE - Descrypt Vaulted HOST YAML file"
  command: "ansible-vault decrypt --vault-password-file {{ vault_file }} {{ inventory_dir }}/host_vars/{{ inventory_hostname }}.yml"
  delegate_to: 127.0.0.1
  when: "'ANSIBLE_VAULT' in host_yaml.stdout"

- name: "RESTORE - Be sure to set 'idp_ldap_restore' to 'False'"
  lineinfile:
   path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}.yml"
   regexp: '^idp_ldap_restore'
   line: 'idp_ldap_restore: "false"'
  delegate_to: 127.0.0.1

- name: "RESTORE - Encrypt HOST YAML file with Vault"
  command: "ansible-vault encrypt --vault-password-file {{ vault_file }} {{ inventory_dir }}/host_vars/{{ inventory_hostname }}.yml"
  delegate_to: 127.0.0.1
  when: "'ANSIBLE_VAULT' in host_yaml.stdout"
