---
# tasks file for pla-install
- name: "Run 'apt-get update' if the last one is more than 3600 seconds ago"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: "Be sure that phpLDAPadmin required packages are installed"
  apt:
   name: "{{ item }}"
   state: latest
   install_recommends: no 
  with_items:
   - apache2-utils
   - python-passlib
   - gettext
  notify:
   - "Restart Apache"

- name: "Be sure that PHP5 LDAP support is installed"
  apt:
   name: "php5-ldap"
   state: latest
   install_recommends: no
  notify:
   - "Restart Apache"
  when: ansible_distribution_release == "jessie"

- name: "Be sure that PHP7 LDAP support is installed"
  apt:
   name: "php7.0-ldap"
   state: latest
   install_recommends: no
  notify:
   - "Restart Apache"
  when: ansible_distribution_release == "stretch"

- name: "Be sure to have LDAP module enabled"
  apache2_module:
   name: "ldap"
   state: present
  notify:
   - "Restart Apache"

- name: "Be sure that phpLDAPadmin is installed"
  unarchive:
   src: "files/phpldapadmin.tar.gz"
   dest: "/opt/"
  changed_when: False

- name: "Be sure to patch files of phpLDAPadmin"
  patch:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
  with_items:
   - { src: "files/phpldapadmin/lib/ds_ldap-idpcloud.patch" ,dest: "/opt/phpldapadmin/lib/ds_ldap.php" }
   - { src: "files/phpldapadmin/lib/ds_ldap_pla-idpcloud.patch" ,dest: "/opt/phpldapadmin/lib/ds_ldap_pla.php" }
   - { src: "files/phpldapadmin/lib/HTMLTree-idpcloud.patch" ,dest: "/opt/phpldapadmin/lib/HTMLTree.php" }
   - { src: "files/phpldapadmin/lib/functions-idpcloud.patch" ,dest: "/opt/phpldapadmin/lib/functions.php" }
   - { src: "files/phpldapadmin/lib/PageRender.patch" ,dest: "/opt/phpldapadmin/lib/PageRender.php" }
   - { src: "files/phpldapadmin/lib/TemplateRender.patch" ,dest: "/opt/phpldapadmin/lib/TemplateRender.php" }
  changed_when: False
