---
# tasks file for apache
- name: "Add Apache user 'www-data' to 'ssl-cert' group"
  user:
   name: "www-data"
   groups: "ssl-cert"

- name: "Be sure to have Apache modules alias, SSL, include, negotiation, headers and Proxy enabled"
  apache2_module:
   name: "{{ item }}"
   state: present
  with_items:
   - alias
   - ssl
   - include
   - negotiation
   - headers
   - proxy_http
  notify:
   - "Restart Apache"

- name: "Modify and Enable default SSL Apache configuration"
  template:
   src: default-ssl.conf.j2
   dest: /etc/apache2/sites-enabled/default-ssl.conf
   owner: "root"
   group: "root"
   mode: "0644"
  notify:
   - "Restart Apache"

- name: "Enable the redirection to HTTPS from all HTTP URL"
  template:
   src: default.conf.j2
   dest: /etc/apache2/sites-enabled/000-default.conf
   owner: "root"
   group: "root"
   mode: "0644"
  notify:
   - "Restart Apache"

- name: "Localize Apache error pages"
  copy:
   src: files/localized-error-pages.conf
   dest: /etc/apache2/conf-enabled/localized-error-pages.conf
   owner: "root"
   group: "root"
   mode: "0644"
  notify:
   - "Restart Apache"

- name: "Restart Apache if CA, CRT or KEY are changed"
  systemd:
   state: restarted
   name: apache2
   daemon_reload: True
  when: 
   - ssl_cert['changed'] == True or ssl_key['changed'] == True or ssl_ca['changed'] == True
