---
# tasks file for idm-configure

- name: "Be sure to copy needed PLA changed libraries"
  copy:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "root"
   group: "root"
   mode: "{{ item.mode }}"
  with_items:
   - { src: "files/phpldapadmin/lib/page.php", dest: "/opt/phpldapadmin/lib/page.php", mode: "0644" }
   - { src: "files/phpldapadmin/lib/pageOrig.php", dest: "/opt/phpldapadmin/lib/pageOrig.php", mode: "0644" }
   - { src: "files/phpldapadmin/lib/TemplateRender.php", dest: "/opt/phpldapadmin/lib/TemplateRender.php", mode: "0644" }
   - { src: "files/phpldapadmin/lib/TemplateRenderOrig.php", dest: "/opt/phpldapadmin/lib/TemplateRenderOrig.php", mode: "0644" }
  changed_when: False

- name: "Be sure to copy needed PLA changed javascripts"
  copy:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "root"
   group: "root"
   mode: "{{ item.mode }}"
  with_items:
   - { src: "files/phpldapadmin/htdocs/js/homeJavascript.js", dest: "/opt/phpldapadmin/htdocs/js/homeJavascript.js", mode: "0644" }
   - { src: "files/phpldapadmin/htdocs/js/formJavascript.js", dest: "/opt/phpldapadmin/htdocs/js/formJavascript.js", mode: "0644" }
   - { src: "files/phpldapadmin/htdocs/js/jquery-1.9.1.min.js", dest: "/opt/phpldapadmin/htdocs/js/jquery-1.9.1.min.js", mode: "0644" }
   - { src: "files/phpldapadmin/htdocs/js/jquery.min.map", dest: "/opt/phpldapadmin/htdocs/js/jquery.min.map", mode: "0644" }
   - { src: "files/phpldapadmin/htdocs/js/jquery-ui-1.9.1.min.js", dest: "/opt/phpldapadmin/htdocs/js/jquery-ui-1.9.1.min.js", mode: "0644" }
   - { src: "files/phpldapadmin/htdocs/js/livevalidation_standalone.compressed.js", dest: "/opt/phpldapadmin/htdocs/js/livevalidation_standalone.compressed.js", mode: "0644" }

- name: "Be sure to patch files of phpLDAPadmin"
  patch:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
  with_items:
   - { src: "files/phpldapadmin/htdocs/create-idpcloud.patch" ,dest: "/opt/phpldapadmin/htdocs/create.php" }
  changed_when: False

- name: "Be sure to copy 'checkValue.php' on phpldapadmin/htdocs"
  template:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "root"
   group: "root"
   mode: "{{ item.mode }}"
  with_items:
   - { src: "phpldapadmin/htdocs/checkValue.php.j2", dest: "/opt/phpldapadmin/htdocs/checkValue.php", mode: "0644" }

- name: "Be sure to add needed files for locking/unlocking users"
  template:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "root"
   group: "root"
   mode: "{{ item.mode }}"
  with_items:
   - { src: "phpldapadmin/htdocs/lockuser.php.j2", dest: "/opt/phpldapadmin/htdocs/lockuser.php", mode: "0644" }
   - { src: "lockusers.py.j2", dest: "/etc/cron.hourly/lockusers.py", mode: "0755" }
   - { src: "phpldapadmin/htdocs/action_lock.php.j2", dest: "/opt/phpldapadmin/htdocs/action_lock.php", mode: "0644" }

- name: "Be sure to update configuration of phpLDAPadmin"
  template:
   src: phpldapadmin/config/config.php.j2
   dest: /opt/phpldapadmin/config/config.php
   owner: "root"
   group: "www-data"
  changed_when: False

- name: "Be sure to add creation/modification PLA templates"
  template:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "root"
   group: "www-data"
   mode: "{{ item.mode }}"
  with_items:
   - { src: "phpldapadmin/templates/creation/custom_idpAccount_{{ idpcloud_garr['idm'] }}.xml.j2", dest: "/opt/phpldapadmin/templates/creation/custom_idpAccount.xml", mode: "0640" }
   - { src: "phpldapadmin/templates/modification/custom_idpAccount_{{ idpcloud_garr['idm'] }}.xml.j2", dest: "/opt/phpldapadmin/templates/modification/custom_idpAccount.xml", mode: "0640" }
 
- name: "Be sure to enrich phpLDAPadmin with IdP-in-the-Cloud italian templates translation"
  copy:
   src: "files/phpldapadmin/locale/it_IT/LC_MESSAGES/messages-it_{{ idpcloud_garr['idm'] }}.mo"
   dest: "/opt/phpldapadmin/locale/it_IT/LC_MESSAGES/messages.mo"
   owner: "root"
   group: "root"
   mode: "0644"
  changed_when: False

- name: "Be sure to create 'idm-tools' directory"
  file:
   path: "/opt/phpldapadmin/htdocs/idm-tools"
   state: directory
   mode: 0755

- name: "Be sure to load idm-tools index page"
  template:
   src: "phpldapadmin/htdocs/idm-tools/index.php.j2"
   dest: "/opt/phpldapadmin/htdocs/idm-tools/index.php"
   owner: "root"
   group: "root"
   mode: "0644"
  notify:
   - "Restart Apache"

- name: "Be sure to load custom CSS for IdP-in-the-Cloud italian templates"
  copy:
   src: "files/phpldapadmin/htdocs/css/default/custom.css"
   dest: "/opt/phpldapadmin/htdocs/css/default/custom.css"
   owner: "root"
   group: "root"
   mode: "0644"

- name: "Be sure to load 'idm-tools' apache2 configuration files"
  copy:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "root"
   group: "root"
   mode: "0644"
  with_items:
   - { src: "files/apache2/conf-enabled/idm-tools.conf", dest: "/etc/apache2/conf-enabled/idm-tools.conf"  }
  notify:
   - "Restart Apache"

- name: "Be sure to load 'statistics' apache2 configuration files"
  copy:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "root"
   group: "root"
   mode: "0644"
  with_items:
   - { src: "files/apache2/conf-enabled/statistics.conf", dest: "/etc/apache2/conf-enabled/statistics.conf"  }
  notify:
   - "Restart Apache"

- name: "Be sure to have 'updates.txt' file for users' updates"
  lineinfile:
   dest: "/var/local/backups/updates.txt"
   line: "{{ item.line }}"
   create: "yes"
   state: present
  with_items:
   - { line: "# Data: " }
   - { line: "" }
   - { line: "Nuovi utenti per {{ ldap['org'] }}:" }

- name: "Be sure to have an Hard Link for 'updates.txt' file"
  file:
   src: "/var/local/backups/updates.txt"
   dest: "/opt/phpldapadmin/htdocs/idm-tools/updates.txt"
   state: hard
