---
# tasks file for check_mk-configure

- name: "Add the IdP host to check_mk server"
  uri:
   url: "https://{{ check_mk['srv'] }}/{{ check_mk['site'] }}/check_mk/webapi.py?action=add_host&_username={{ check_mk['api_user_name'] }}&_secret={{ check_mk['api_user_secret'] }}&folder={{ check_mk['folder'] }}&hostname={{ fqdn }}"
   method: GET 
   status_code: 200
   headers:
     Content-Type: "application/json; charset=UTF-8"
  when:
   - fqdn is defined and fqdn != ""
   - check_mk is defined
   - check_mk['check_idp'] is defined and check_mk['check_idp'] in ["True","true","Yes","yes"]
   - check_mk['srv'] is defined and check_mk['srv'] != ''
   - check_mk['site'] is defined and check_mk['site'] != ''
   - check_mk['api_user_name'] is defined and check_mk['api_user_name'] != ''
   - check_mk['api_user_secret'] is defined and check_mk['api_user_secret'] != ''
   - check_mk['folder'] is defined and check_mk['folder'] != ''

- name: "Remove the IdP host from checking on check_mk server"
  uri:
   url: "https://{{ check_mk['srv'] }}/{{ check_mk['site'] }}/check_mk/webapi.py?action=delete_host&_username={{ check_mk['api_user_name'] }}&_secret={{ check_mk['api_user_secret'] }}&hostname={{ fqdn }}"
   method: GET 
   status_code: 200
   headers:
     Content-Type: "application/json; charset=UTF-8"
  when:
   - fqdn is defined and fqdn != ""
   - check_mk is defined
   - check_mk['check_idp'] is defined and check_mk['check_idp'] in ["False","false","No","no"]
   - check_mk['srv'] is defined and check_mk['srv'] != ''
   - check_mk['site'] is defined and check_mk['site'] != ''
   - check_mk['api_user_name'] is defined and check_mk['api_user_name'] != ''
   - check_mk['api_user_secret'] is defined and check_mk['api_user_secret'] != ''

- name: "Activate changes on Check_MK centralized server"
  uri:
   url: "https://{{ check_mk['srv'] }}/{{ check_mk['site'] }}/check_mk/webapi.py?action=activate_changes&_username={{ check_mk['api_user_name'] }}&_secret={{ check_mk['api_user_secret'] }}"
   method: GET 
   status_code: 200
   headers:
     Content-Type: "application/json; charset=UTF-8"
  when:
   - fqdn is defined and fqdn != ""
   - check_mk is defined
   - check_mk['srv'] is defined and check_mk['srv'] != ''
   - check_mk['site'] is defined and check_mk['site'] != ''
   - check_mk['api_user_name'] is defined and check_mk['api_user_name'] != ''
   - check_mk['api_user_secret'] is defined and check_mk['api_user_secret'] != ''
